# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen_ytb_dowloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ytb_dowloader as download


class Ui_ytb_dowloader(object):
    def setupUi(self, ytb_dowloader):
        ytb_dowloader.setObjectName("ytb_dowloader")
        ytb_dowloader.resize(650, 450)
        ytb_dowloader.setMinimumSize(QtCore.QSize(650, 450))
        ytb_dowloader.setMaximumSize(QtCore.QSize(600, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("youtube-logo.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ytb_dowloader.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(ytb_dowloader)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pesquisa = QtWidgets.QFrame(ytb_dowloader)
        self.pesquisa.setMaximumSize(QtCore.QSize(550, 50))
        self.pesquisa.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pesquisa.setStyleSheet(
            "alternate-background-color: rgba(255, 255, 255, 2);")
        self.pesquisa.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pesquisa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pesquisa.setObjectName("pesquisa")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.pesquisa)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QLabel(self.pesquisa)
        self.logo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("youtube-logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.label_link = QtWidgets.QLabel(self.pesquisa)
        self.label_link.setMinimumSize(QtCore.QSize(50, 0))
        self.label_link.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_link.setAutoFillBackground(False)
        self.label_link.setIndent(21)
        self.label_link.setObjectName("label_link")
        self.horizontalLayout.addWidget(self.label_link)
        self.pesq_link = QtWidgets.QLineEdit(self.pesquisa)
        self.pesq_link.setMaximumSize(QtCore.QSize(450, 16777215))
        self.pesq_link.setObjectName("pesq_link")
        self.horizontalLayout.addWidget(self.pesq_link)
        self.verticalLayout.addWidget(self.pesquisa)
        self.info_frame = QtWidgets.QFrame(ytb_dowloader)
        self.info_frame.setAutoFillBackground(False)
        self.info_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.info_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.tam_video = QtWidgets.QLabel(self.info_frame)
        self.tam_video.setMaximumSize(QtCore.QSize(110, 50))
        self.tam_video.setObjectName("tam_video")
        self.gridLayout.addWidget(self.tam_video, 2, 0, 1, 1)
        self.dt_time_repr = QtWidgets.QLabel(self.info_frame)
        self.dt_time_repr.setMaximumSize(QtCore.QSize(16777215, 50))
        self.dt_time_repr.setObjectName("dt_time_repr")
        self.gridLayout.addWidget(self.dt_time_repr, 1, 1, 1, 1)
        self.img_video = QtWidgets.QLabel(self.info_frame)
        self.img_video.setMaximumSize(QtCore.QSize(110, 16777215))
        self.img_video.setObjectName("img_video")
        self.gridLayout.addWidget(self.img_video, 3, 0, 1, 1)
        self.titulo = QtWidgets.QLabel(self.info_frame)
        self.titulo.setMaximumSize(QtCore.QSize(110, 50))
        self.titulo.setObjectName("titulo")
        self.gridLayout.addWidget(self.titulo, 0, 0, 1, 1)
        self.dt_title = QtWidgets.QLabel(self.info_frame)
        self.dt_title.setMaximumSize(QtCore.QSize(16777215, 50))
        self.dt_title.setObjectName("dt_title")
        self.gridLayout.addWidget(self.dt_title, 0, 1, 1, 1)
        self.reprud_time = QtWidgets.QLabel(self.info_frame)
        self.reprud_time.setMaximumSize(QtCore.QSize(150, 50))
        self.reprud_time.setObjectName("reprud_time")
        self.gridLayout.addWidget(self.reprud_time, 1, 0, 1, 1)
        self.dt_img = QtWidgets.QLabel(self.info_frame)
        self.dt_img.setMaximumSize(QtCore.QSize(300, 170))
        self.dt_img.setText("")
        self.dt_img.setPixmap(QtGui.QPixmap("youtube-logo.png"))
        self.dt_img.setScaledContents(True)
        self.dt_img.setObjectName("dt_img")
        self.gridLayout.addWidget(self.dt_img, 3, 1, 1, 1)
        self.dt_tam = QtWidgets.QLabel(self.info_frame)
        self.dt_tam.setMaximumSize(QtCore.QSize(16777215, 50))
        self.dt_tam.setObjectName("dt_tam")
        self.gridLayout.addWidget(self.dt_tam, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.info_frame)
        self.load_frame = QtWidgets.QFrame(ytb_dowloader)
        self.load_frame.setMaximumSize(QtCore.QSize(600, 50))
        self.load_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.load_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.load_frame.setObjectName("load_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.load_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.load_frame)
        self.progressBar.setMaximumSize(QtCore.QSize(600, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.load_frame)
        self.baixar = QtWidgets.QPushButton(ytb_dowloader)
        self.baixar.setMaximumSize(QtCore.QSize(580, 16777215))
        self.baixar.setObjectName("baixar")
        self.verticalLayout.addWidget(self.baixar)


        self.baixar.clicked.connect(lambda: download.download(self.pesq_link.text()))

        self.retranslateUi(ytb_dowloader)
        QtCore.QMetaObject.connectSlotsByName(ytb_dowloader)



        #-------------------------------------------

        

    def retranslateUi(self, ytb_dowloader):
        _translate = QtCore.QCoreApplication.translate
        ytb_dowloader.setWindowTitle(_translate(
            "ytb_dowloader", "DOWLOAD YOUTUBE"))
        self.label_link.setText(_translate("ytb_dowloader", "LINK:"))
        self.tam_video.setText(_translate(
            "ytb_dowloader", "Tamanho do vídeo:"))
        self.dt_time_repr.setText(_translate("ytb_dowloader", "TextLabel"))
        self.img_video.setText(_translate("ytb_dowloader", "Imagem:"))
        self.titulo.setText(_translate("ytb_dowloader", "Título:"))
        self.dt_title.setText(_translate("ytb_dowloader", "TextLabel"))
        self.reprud_time.setText(_translate(
            "ytb_dowloader", "Tempo de reprodução:"))
        self.dt_tam.setText(_translate("ytb_dowloader", "TextLabel"))
        self.progressBar.setFormat(_translate("ytb_dowloader", "%p%"))
        self.baixar.setText(_translate("ytb_dowloader", "Baixar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ytb_dowloader = QtWidgets.QWidget()
    ui = Ui_ytb_dowloader()
    ui.setupUi(ytb_dowloader)
    ytb_dowloader.show()
    sys.exit(app.exec_())
